name: Naoki Ueda

highlighter: pygments

permalink: /:categories/:year-:month-:day/:title/
pygments: true
markdown: redcarpet

redcarpet:
  fenced_code_blocks: true

excerpt_separator: "\n\n" # why?

